### ISSUE TITLE
Results don't appear in fzf immediately on large projects

### ISSUE THREAD

**Issue by gianfrappe** [jesseleite/vim-agriculture#11]
I'm having a problem when using vim-agriculture on large projects. As with the default `fzf` `Rg` command, the `fzf` window load instantly, but the matches appear with time as `ripgrep` finds result. I wonder if it would be possible to make `fzf` wait for `RgRaw` to complete or alternatively to show the completion percentage in the `fzf` window. I would like to replace `vim-grepper` workflow with just using `fzf.vim` with `vim-agriculture`, but I am never sure if `ripgrep` is still searching for matches or not, as when I add items to the quickfix list with `Alt+a`, every subsequent match is just ignored.

**Comment by jesseleite** [comment]
Sorry for the delay in reply here! I think this is out of scope to vim-agriculture, as I'm really just wrapping fzf.vim's `:Ag` behaviour. I'm really not sure if there's anything I could do to remedy this problem. Maybe post an issue in fzf.vim's repo and see if you get any feedback there? Anyway, going to close this now as I'm not sure it'a actionable on my end, at the moment anyway.
