### ISSUE TITLE
Search in current buffer

### ISSUE THREAD

**Issue by uolot** [jesseleite/vim-agriculture#3]
Hi, thanks for this nice plugin and accompanying blog post, good work!

I have a small command that searches for todos in current buffer, with `ack.vim` the following worked just fine:
```
command Todos Ack! '(TODO|XXX|FIXME)' %
```
but I can't make it work after replacing `Ack!` with `AgRaw`. 

I tried `%` and `expand('%')`. The former results in a list with line numbers and contents of matching line and column numbers, but no filename (`123:3:# TODO something`), making it impossible to jump to the given match -- it just opens a new file with line number as a name. 
The latter errors with `E484: Cannot open file /tmp/vmYrqvV/5`.

I tried adding `--filename` option, but it doesn't seem to change anything (TBH it also does't print the filename when searching in a single file with ag in the terminal).

Adding `--vimgrep` seems to do the trick, but it removes match highlighting.

Do you have any ideas on how to fix it?

**Comment by uolot** [comment]
After I wrote down my question, I've managed to find the answer a couple minutes later. Adding `--noheading` does the trick.

**Comment by jesseleite** [comment]
Oh cool, and thank you for kind words!  Share your final command?  I'd love to see!

**Comment by uolot** [comment]
Sure thing, this works as expected:
```
command Todos AgRaw --noheading '(TODO|XXX|FIXME)' %
```

**Comment by uolot** [comment]
A small update, it's just evolved into:
```
command -nargs=+ AgRawBuf AgRaw --noheading <args> %
command -nargs=0 Todos AgRawBuf '(TODO|XXX|FIXME)'
```

**Comment by jesseleite** [comment]
Nice and simple 👍 . I would add `--noheading` as a default, but it messes with multi-file searches.
