### ISSUE TITLE
how to make it always search from project root

### ISSUE THREAD

**Issue by yyb196** [jesseleite/vim-agriculture#7]
I have a project has file struct like this:
project->a->b
`          `L--- ->c->d

when i open b in vim i need to search in the whole project? how can i do that.

**Comment by jesseleite** [comment]
Agriculture is just a wrapper for fzf.vim, and that's how fzf.vim inherently works.  You'd have to either change your vim session's pwd (see `:help pwd`), or get into a workflow of opening vim at your project root.

Personally, I prefer always opening vim at my project root.  When I need to open deeply nested files, that's what fzf.vim's `:GFiles` and `:Files` fuzzy finders are for.

Hope it helps!  🙂

**Comment by kabeersvohra** [comment]
Btw if you have this and you find yourself opening files not from git root, this will set the `pwd` back to root whenever you open the file - https://github.com/airblade/vim-rooter.

Cheers for the great plugin @jesseleite, been using your workflow for a long time and love it

**Comment by jesseleite** [comment]
Thanks for the kind words @kabeersvohra!
