### ISSUE TITLE
How to preview file on the quickfix list without jumping out of it?

### ISSUE THREAD

**Issue by dagadbm** [jesseleite/vim-agriculture#8]
I know this is not really a vim-agriculture problem but I wanted to know how can I preview the quickfix list file without jumping out of it?

I am using your plugin together with quickfix-reflector for  a more seamless edit experience on the quickfix list

**Comment by jesseleite** [comment]
Nice, how'd you find out about vim-agriculture btw?

Fzf-like previews would be impossible in the quickfix without some sort of quickfix preview plugin.  Not sure if one exists.

Or maybe you just want to preview the file in the above window without losing quickfix focus... Then you could make a quickfix mapping that would let you open the file, then immediately switch back to the last window (your quickfix window).

**Comment by dagadbm** [comment]
Oh good One. How can I know the last window I was on? Any easy binding to
do that or would I need to code?

I thought vim-agriculture was well known.

Probably one of those reddit posts after googling a way for a more fluent
find and replace workflow .

I ended up using vimgrep and it took me forever to understand I didn't need
it lol I could just use this one which I'm guessing is newer .
Technically the only reason why I use this plugin is to support the %
expand which I can't get to work on fzf.

**Comment by jesseleite** [comment]
`<C-w><C-p>` will select your last focused window.

**Comment by jesseleite** [comment]
Closing this as an issue, but not discouraging discussion 🙂
